### ISSUE TITLE
tip: emacs-python-pytest

### ISSUE THREAD

**Issue by wbolster** [ionrock/pytest-el#25]
hey, you may be interested in my emacs python pytest project:
https://github.com/wbolster/emacs-python-pytest

it serves the same use case as this package. i think it does everything this package does, and more, with a nice interface on top!

**Comment by ionrock** [comment]
@wbolster Great tip! I don't really work in python as much as I used to, so folks should definitely take a look. Also, I noticed you took a similar tactic regarding the setting the path for virtualenvs. I worked on combating that with my [we](https://github.com/ionrock/we) and [xenv](https://github.com/ionrock/xenv) projects. The idea being you have some tooling to inject configuration at runtime that you can use in development, all the way to production. It is a similar take as direnv and your emacs direnv package.

I'll be sure to try out emacs-python-pytest next time I'm working in Python!
