### ISSUE TITLE
Add support for Fish shell

### ISSUE THREAD

**Issue by jramnani** [ionrock/pytest-el#5]
Hello,

I use fish as my login shell and wanted to use pytest-el.  The command, "pytest-all", emits an error when run within fish shell.

The error occurs because fish shell doesn't support the "&&" syntax to chain commands together.  It uses the "and" keyword instead.

I've created a pull request (#4) if you would like to add support.  I've run tests on my workstation using both Fish and Bash, but you probably should test to make sure that I haven't broken anything.  Feedback on the PR is welcome.

Thanks for publishing pytest-el.  I find it really useful.

Have a nice day.

Jeff Ramnani

**Comment by ionrock** [comment]
@jramnani I'm assuming #4 should let us close this issue? If so please feel free to close it. Thanks!

**Comment by jramnani** [comment]
Fixed by merging in PR #10.

Thanks!
